<a href="https://colab.research.google.com/github/syedabdulqadirgilani/-Deep-Learning-Assignments/blob/main/Python%2CNumpy%2CPandas_%26_Matplotlib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
import pandas as pd

In [9]:
print(pd.__version__,'pd\n',np.__version__,'np')

1.1.5 pd
 1.19.5 np


In [10]:
%time for a in range(1,10): r=[n*5 for n in range(2000000)]

CPU times: user 1.53 s, sys: 405 ms, total: 1.94 s
Wall time: 1.95 s


In [12]:
%time for b in range(1,10): r=range((2000000)*5)

CPU times: user 27.1 ms, sys: 7.09 ms, total: 34.2 ms
Wall time: 34.1 ms


In [15]:
np.zeros(14)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
type(np.zeros(14))

numpy.ndarray

In [17]:
type(np.zeros(14)[0])

numpy.float64

In [18]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
np.empty(10)

array([4.64532743e-310, 4.64532630e-310, 4.64532630e-310, 4.64532630e-310,
       4.64532630e-310, 4.64532630e-310, 4.64532630e-310, 4.64532630e-310,
       0.00000000e+000, 0.00000000e+000])

In [20]:
type(np.empty(10))

numpy.ndarray

In [21]:
np.empty(10).dtype

dtype('float64')

In [22]:
np.empty(10).shape

(10,)

In [28]:
n=np.empty(10)
e=n.shape=(5,2)
e

(5, 2)

In [32]:
np.linspace(3,200,5)

array([  3.  ,  52.25, 101.5 , 150.75, 200.  ])

In [33]:
np.arange(3,200,5)

array([  3,   8,  13,  18,  23,  28,  33,  38,  43,  48,  53,  58,  63,
        68,  73,  78,  83,  88,  93,  98, 103, 108, 113, 118, 123, 128,
       133, 138, 143, 148, 153, 158, 163, 168, 173, 178, 183, 188, 193,
       198])

In [34]:
np.array((10,20,30))

array([10, 20, 30])

In [40]:
l=[[1,2,3,4,5,6,7],[1,2,3,4,5,6,7]]
na=np.array(l)
na

array([[1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7]])

In [41]:
na.shape

(2, 7)

In [43]:
?na.shape

In [45]:
ra=np.random.randint(10,size=10)
ra

array([8, 5, 3, 1, 7, 3, 1, 6, 0, 1])

In [46]:
ra[0]

8

In [47]:
ra[-1]

1

In [48]:
ra[0:5]

array([8, 5, 3, 1, 7])

In [49]:
ra>10

array([False, False, False, False, False, False, False, False, False,
       False])

In [51]:
ra[ra>40]

array([], dtype=int64)

In [52]:
ra*2

array([16, 10,  6,  2, 14,  6,  2, 12,  0,  2])

In [53]:
ra+100

array([108, 105, 103, 101, 107, 103, 101, 106, 100, 101])

In [54]:
ra-100

array([ -92,  -95,  -97,  -99,  -93,  -97,  -99,  -94, -100,  -99])

In [55]:
ra/2

array([4. , 2.5, 1.5, 0.5, 3.5, 1.5, 0.5, 3. , 0. , 0.5])

In [56]:
ra*ra

array([64, 25,  9,  1, 49,  9,  1, 36,  0,  1])

In [57]:
l=[1,2,3,4]
l*2

[1, 2, 3, 4, 1, 2, 3, 4]

In [58]:
ra*2

array([16, 10,  6,  2, 14,  6,  2, 12,  0,  2])

In [59]:
ra+5

array([13, 10,  8,  6, 12,  8,  6, 11,  5,  6])

In [60]:
l+5

TypeError: ignored

In [61]:
ra@ra

195

In [64]:
a=np.array([1,2,3,4,5,6,7,8])
b=np.array([7,2,1,3,4,5,8,7])

In [65]:
np.where(a>b,a,b)

array([7, 2, 3, 4, 5, 6, 8, 8])

In [66]:
r=np.array([44,42,25,30,50,70,20])
np.where(r>40,'p','f')

array(['p', 'p', 'f', 'f', 'p', 'p', 'f'], dtype='<U1')

In [67]:
np.array([1,2,3,4,5,6,7,8,9,10]).mean()

5.5

In [68]:
np.array([1,2,3,4,5,6,7,8,9,10]).cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [69]:
np.array([1,2,3,4,5,6,7,8,9,10]).cumprod()

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800])

In [70]:
np.array([1,2,3,4,5,6,7,8,9,10]).sum()

55

In [71]:
np.array([1,2,3,4,5,6,7,8,9,10])>11

array([False, False, False, False, False, False, False, False, False,
       False])

In [75]:
np.array([1,2,3,4,5,6,7,8,9,10]).any()

True

In [76]:
np.array([1,2,3,4,5,6,7,8,9,10]).all()

True

In [80]:
s=np.array([3,2,2,1]).sort()
s

In [82]:
np.unique([1,2,3,4,5,5,5,5])

array([1, 2, 3, 4, 5])

In [83]:
np.save('a.npy',np.array([1,2,3,4,5]))

In [84]:
np.load('a.npy')

array([1, 2, 3, 4, 5])

In [89]:
np.savez('a',a=np.array([1,2,3]),b=np.array([3,4,5]))

In [91]:
np.load('a.npz')

In [96]:
np.dot([1,2,3,4],[5,6,7,8])

70

In [97]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [100]:
np.array([[1,2,3],[4,5,6]]).transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [103]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [113]:
np.trace([[1,2,3,4,5]])

1

In [117]:
a=np.array([1,2])
b=np.array([4,5])
np.linalg.det((a,b))

-2.9999999999999996

In [126]:
np.random.randint(100,size=(13))

array([51, 81, 53, 26, 56, 57, 77, 68,  3, 35, 13, 61,  7])

In [129]:
np.random.normal(9,size=(5,2))

array([[ 8.730909  ,  8.45429812],
       [ 9.73402014,  8.09542578],
       [ 8.06443896, 11.45044292],
       [ 9.3409146 , 10.98751717],
       [ 7.32832683,  8.09532419]])

In [130]:
np.random.gamma(9,size=(2,3))

array([[ 4.24241723, 10.89370527,  8.9319374 ],
       [12.0485677 , 10.11652102,  7.92687558]])

In [131]:
np.random.seed(10)

In [132]:
np.random.gamma(3,size=5)

array([5.48572926, 4.01355368, 3.8154306 , 1.65514449, 3.1241686 ])

In [134]:
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [137]:
np.arange(1,13).reshape(3,4,order='f')

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [138]:
np.arange(1,13).reshape(3,4,order='c')

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [139]:
np.arange(1,13).reshape(2,3,2,order='c')

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [140]:
np.arange(1,13).reshape(2,3,2,order='f')

array([[[ 1,  7],
        [ 3,  9],
        [ 5, 11]],

       [[ 2,  8],
        [ 4, 10],
        [ 6, 12]]])

In [141]:
np.arange(1,13).reshape(2,3,2,order='f').ravel()

array([ 1,  7,  3,  9,  5, 11,  2,  8,  4, 10,  6, 12])

In [142]:
np.arange(1,13).reshape(2,3,2,order='c').ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [143]:
np.arange(1,13).reshape(2,3,2,order='c').flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [144]:
a=np.arange(1,5)

In [145]:
a

array([1, 2, 3, 4])

In [146]:
b=np.arange(6,10)

In [147]:
np.concatenate((a,b))

array([1, 2, 3, 4, 6, 7, 8, 9])

In [148]:
np.hstack((a,b))

array([1, 2, 3, 4, 6, 7, 8, 9])

In [149]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [152]:
c=np.arange(1,15)
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [153]:
np.split(c,[3,8])

[array([1, 2, 3]), array([4, 5, 6, 7, 8]), array([ 9, 10, 11, 12, 13, 14])]

In [154]:
rot=np.array([1,5,7,8])
np.repeat(rot,3)

array([1, 1, 1, 5, 5, 5, 7, 7, 7, 8, 8, 8])

In [155]:
np.tile(rot,3)

array([1, 5, 7, 8, 1, 5, 7, 8, 1, 5, 7, 8])

In [157]:
pd.Series([1,2,3,4],index=['a','b','c','d'])

a    1
b    2
c    3
d    4
dtype: int64

In [158]:
pd.Series([1,2,3,4],index=['a','b','c','d']).values

array([1, 2, 3, 4])

In [159]:
pd.Series([1,2,3,4],index=['a','b','c','d']).index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [160]:
s1=pd.Series([1,2,3,4],index=['a','b','c','d'])
s1[1]

2